version: '3.9'
services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: luma
      POSTGRES_PASSWORD: luma
      POSTGRES_DB: luma
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U luma"]
      interval: 5s
      timeout: 3s
      retries: 5
  backend:
    build: ./backend
    command: node dist/main.js
    env_file: ./backend/.env
    ports:
      - '3000:3000'
    depends_on:
      db:
        condition: service_healthy
      seed:
        condition: service_completed_successfully
  seed:
    build: ./backend
    command: node dist/seed.js
    depends_on:
      db:
        condition: service_healthy
volumes:
  db-data:
