version: '3.9'
services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: luceam
      POSTGRES_PASSWORD: luceam
      POSTGRES_DB: luceam
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U luceam"]
      interval: 5s
      timeout: 3s
      retries: 5
  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'
    command: ["redis-server", "--appendonly", "no", "--maxmemory", "512mb", "--maxmemory-policy", "allkeys-lru"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10
  backend:
    build: ./backend
    command: node dist/main.js
    env_file: ./backend/.env
    ports:
      - '3000:3000'
    depends_on:
      db:
        condition: service_healthy
      seed:
        condition: service_completed_successfully
      redis:
        condition: service_healthy
  seed:
    build: ./backend
    command: node dist/seed.js
    depends_on:
      db:
        condition: service_healthy
volumes:
  db-data:
