services:
  db:
    image: postgres:16
    container_name: luceamios-db-1
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-luceam}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 20

  redis:
    image: redis:7-alpine
    container_name: luceamios-redis-1
    ports:
      - "6379:6379" # optional: nur nötig, wenn du lokal von außerhalb zugreifen willst
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 20

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: luceamios-backend-1
    env_file:
      - .env
    environment:
      NODE_ENV: ${NODE_ENV}
      PORT: ${PORT}
      # Primary connection string with safe default
      DATABASE_URL: ${DATABASE_URL:-postgresql://postgres:postgres@db:5432/luceam}
      # Common explicit vars (for TypeORM/Prisma configs that don't use DATABASE_URL)
      POSTGRES_DB: ${POSTGRES_DB:-luceam}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      DB_HOST: ${DB_HOST:-db}
      DB_PORT: ${DB_PORT:-5432}
      DB_USER: ${DB_USER:-postgres}
      DB_USERNAME: ${DB_USERNAME:-postgres}
      DB_PASS: ${DB_PASS:-postgres}
      DB_PASSWORD: ${DB_PASSWORD:-postgres}
      DB_NAME: ${DB_NAME:-luceam}
      # Redis
      REDIS_URL: ${REDIS_URL}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      # Presence simulator (server-side)
      SIM_PRESENCE_ENABLED: ${SIM_PRESENCE_ENABLED}
      SIM_PRESENCE_MIN: ${SIM_PRESENCE_MIN}
      SIM_PRESENCE_MAX: ${SIM_PRESENCE_MAX}
      SIM_PRESENCE_STEP_MS: ${SIM_PRESENCE_STEP_MS}
      SIM_PRESENCE_RISE_RATIO: ${SIM_PRESENCE_RISE_RATIO}
      SIM_PRESENCE_DECAY_AFTER_MS: ${SIM_PRESENCE_DECAY_AFTER_MS}
      SIM_PRESENCE_TTL_SECONDS: ${SIM_PRESENCE_TTL_SECONDS}
      SIM_PRESENCE_MAX_DURATION_MS: ${SIM_PRESENCE_MAX_DURATION_MS}
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "3000:3000"

  seed:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: luceamios-seed-1
    env_file:
      - .env
    environment:
      NODE_ENV: ${NODE_ENV}
      POSTGRES_DB: ${POSTGRES_DB:-luceam}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      DB_PASS: ${DB_PASS:-postgres}
      DATABASE_URL: ${DATABASE_URL:-postgresql://postgres:postgres@db:5432/luceam}
      REDIS_URL: ${REDIS_URL}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: ["npm", "run", "seed"]
    restart: "no"

volumes:
  db-data: